# Generated by Django 5.2.7 on 2025-10-22 01:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('joined_date', models.DateField()),
                ('photo', models.ImageField(default='staff/not_set.png', upload_to='employees/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On leave')], default='active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=40)),
                ('paycheck_period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly')], default='monthly', max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='staff.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='staff.personalprofile'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='staff.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started_yet', 'Not Started Yet'), ('in_progress', 'In Progress'), ('unfinished', 'Paused/Unfinished'), ('done', 'Done')], default='not_started_yet', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to='staff.employee')),
                ('participants', models.ManyToManyField(related_name='projects', through='staff.EmployeeProject', to='staff.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To-Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('reviewed', 'Reviewed')], default='todo', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_employees', models.ManyToManyField(related_name='tasks', through='staff.EmployeeTask', to='staff.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='staff.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.project')),
            ],
        ),
        migrations.AddField(
            model_name='employeetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.task'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('started_role_at_date', models.DateField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('ending_role_at_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('internship', 'Internship')], default='part_time', max_length=15)),
                ('notice_period', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='staff.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ending_role_at_date__isnull', True)), fields=('employee',), name='uniq_current_employment_per_employee')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeproject',
            constraint=models.UniqueConstraint(condition=models.Q(('date_left__isnull', True)), fields=('employee', 'project'), name='uniq_active_employee_project'),
        ),
        migrations.AddConstraint(
            model_name='employeetask',
            constraint=models.UniqueConstraint(condition=models.Q(('date_left__isnull', True)), fields=('employee', 'task'), name='uniq_active_employee_task'),
        ),
    ]
